### ISSUE TITLE
Kubedog gets wrong ReplicaSet

### ISSUE THREAD

**Issue by sh1kel** [werf/kubedog#45]
I get deployment error sometimes.
```2019/02/15 17:55:49 # deploy/marketplace-api added
2019/02/15 17:55:49 # deploy/marketplace-api rs/marketplace-api-7b6bc88574 added
2019/02/15 17:55:49 # deploy/marketplace-api po/marketplace-api-7b6bc88574-phpjd added
2019/02/15 17:55:52 # deploy/marketplace-api FAIL: resource deleted
```

Deploy added at **17:55:49** and it gets ReplicaSet **marketplace-api-7b6bc88574** at **17:55:49**. But it old RS, because new RS was created only in 2s (cluster worked slowly in that time).

That's correct rs.
```kubectl get rs -n mapi
NAME                                                      DESIRED   CURRENT   READY   AGE
marketplace-api-7c5f548fdc                                1         1         1       2d
marketplace-api-fc5cfcf58                                 0         0         0       2d
```
```kubectl describe rs "marketplace-api-fc5cfcf58" -n mapi
Name:           marketplace-api-fc5cfcf58
Namespace:      mapi
Selector:       app=marketplace-api,pod-template-hash=971797914,release=marketplace-api
Labels:         app=marketplace-api
                date=2019-02-15T175551Z\
```

So we have a case when kubedog got earlier RS because right RS was not create fast enough.

**Comment by ilya-lesikov** [comment]
Is this fixed? As far as I know the mechanism for detecting corresponding replicaset and pods for deployments is suboptimal and sometimes may return wrong results, but the issue is not easy to fix.

We will probably reevaluate the mechanism once we get to rework of low-level parts of kubedog. We already did the big rewrite of the high-level kubedog api, which resulted in the new dynamic tracker, but the same needs to be done to low-level trackers.
